import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import pg from "pg";
import dotenv from "dotenv";
import fs from "fs";
import Razorpay from "razorpay";
import crypto from "crypto";
import nodemailer from "nodemailer";


// Load environment variables
dotenv.config();

const { Pool } = pg;

// Get connection string from environment
const connectionString = process.env.DATABASE_URL;

let pool: pg.Pool | null = null;

if (connectionString) {
  console.log("Initializing database pool with connection string...");
  pool = new Pool({
    connectionString,
    ssl: {
      rejectUnauthorized: false // Required for Supabase/hosted databases
    }
  });
} else {
  console.error("WARNING: DATABASE_URL env variable is not set!");
}

async function initializeDatabase() {
  if (!pool) return;
  try {
    console.log("Ensuring database tables exist...");
    
    // Create profiles table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        mobile TEXT NOT NULL,
        name TEXT,
        password TEXT,
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Ensure password column exists if table was already created
    await pool.query(`
      ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS password TEXT;
    `);

    // Ensure created_at and updated_at exist in profiles as well
    await pool.query(`
      ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
    `);
    await pool.query(`
      ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
    `);
    
    // Create orders table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_name TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT NOT NULL,
        company TEXT,
        address TEXT NOT NULL,
        city TEXT NOT NULL,
        zip TEXT NOT NULL,
        items JSONB NOT NULL DEFAULT '[]'::jsonb,
        total_price NUMERIC(10, 2) NOT NULL,
        payment_method TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    
    // Create gifting_requests table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.gifting_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        perfume_id TEXT NOT NULL,
        size TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        recipient_name TEXT NOT NULL,
        message TEXT NOT NULL,
        font_style TEXT NOT NULL,
        ribbon_color TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Create invitations table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.invitations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        vip_code TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Create products table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.products (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        tagline TEXT NOT NULL,
        price NUMERIC(10, 2) NOT NULL,
        size TEXT NOT NULL,
        edition TEXT NOT NULL,
        image_url TEXT NOT NULL,
        description TEXT NOT NULL,
        concentration TEXT,
        longevity TEXT,
        sillage TEXT,
        notes JSONB,
        character JSONB,
        is_limited_edition BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Guard with alters to handle tables created in legacy environments
    if (pool) {
      await pool.query(`ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();`).catch(() => {});
      await pool.query(`ALTER TABLE public.gifting_requests ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();`).catch(() => {});
      await pool.query(`ALTER TABLE public.invitations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();`).catch(() => {});
      await pool.query(`ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();`).catch(() => {});
      await pool.query(`ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_limited_edition BOOLEAN DEFAULT TRUE;`).catch(() => {});
    }

    // Pre-seed initial 3 signature perfumes if products table is empty
    const prodCheck = await pool.query("SELECT COUNT(*) FROM public.products");
    if (parseInt(prodCheck.rows[0].count) === 0) {
      console.log("Seeding initial products into database...");
      
      // Seed MUSE
      await pool.query(`
        INSERT INTO public.products (id, name, type, tagline, price, size, edition, image_url, description, concentration, longevity, sillage, notes, character, is_limited_edition)
        VALUES (
          'muse', 'MUSE', 'women', 'The Visionary Command', 499, '50 ML', 'LIMITED RUN',
          'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
          'The ultimate olfactory signature for the visionary female leader. Muse is a complex, magnetic blend of rare white florals and deep, grounded cedar. It is a fragrance that precedes your words, establishing a magnetic gravity of grace, intelligence, and uncompromising authority.',
          'Premium Parfum', '12+ Hours (Premium Luxury Grade)', 'Commanding & Magnetic',
          '{"top": ["Pink Pepper", "Damask Rose", "Sweet Bergamot"], "heart": ["Jasmine Sambac", "French Iris", "Cashmere Wood"], "base": ["White Patchouli", "Warm Cedarwood", "Rich Ambergris"]}'::jsonb,
          '["Visionary", "Graceful", "Unyielding", "Sophisticated"]'::jsonb,
          true
        );
      `);

      // Seed NEXUS
      await pool.query(`
        INSERT INTO public.products (id, name, type, tagline, price, size, edition, image_url, description, concentration, longevity, sillage, notes, character, is_limited_edition)
        VALUES (
          'nexus', 'NEXUS', 'unisex', 'The Architectural Balance', 499, '50 ML', 'LIMITED RUN',
          'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
          'Built on the principle of balanced intelligence. Nexus is a fluid, architectural fragrance that exists beyond traditional boundaries. Crisp Mediterranean citrus fuses with warm, velvet lavender and deep dry amber to construct an atmosphere of diplomatic precision and intellectual authority.',
          'Premium Parfum', '10-12 Hours', 'Refined & Articulate',
          '{"top": ["Calabrian Bergamot", "Clary Sage", "Juniper Berry"], "heart": ["French Lavender", "Warm Saffron", "Sandalwood"], "base": ["Grey Ambergris", "Haitian Vetiver", "Oakmoss"]}'::jsonb,
          '["Diplomatic", "Balanced", "Intellectual", "Progressive"]'::jsonb,
          true
        );
      `);

      // Seed FORGE
      await pool.query(`
        INSERT INTO public.products (id, name, type, tagline, price, size, edition, image_url, description, concentration, longevity, sillage, notes, character, is_limited_edition)
        VALUES (
          'forge', 'FORGE', 'men', 'The Decisive Resolve', 499, '50 ML', 'LIMITED RUN',
          'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
          'The physical manifestation of absolute resolve. Forge is a powerful, heavy-hitting blend of rich leather, structured vetiver, and dark, warm oud. Specifically formulated for men who build empires out of chaos and carve their strategic vision through sheer focus.',
          'Premium Parfum', '14+ Hours (Extreme Longevity)', 'Powerful & Majestic',
          '{"top": ["Smoky Leather", "Black Cardamom", "Coriander Seed"], "heart": ["Dark Oud Wood", "Virginia Cedar", "Tobacco Leaf"], "base": ["White Musk", "Bourbon Vanilla", "Dry Vetiver"]}'::jsonb,
          '["Decisive", "Commanding", "Indomitable", "Architectural"]'::jsonb,
          true
        );
      `);
      console.log("Seeding products completed successfully!");
    }
    
    console.log("All database tables checked/created successfully!");
  } catch (err) {
    console.error("Database initialization error:", err);
  }
}

// Nodemailer dispatcher to notify svaofficials@gmail.com of new orders
async function sendOrderNotification(order: any) {
  try {
    const host = process.env.SMTP_HOST || "smtp.gmail.com";
    const port = parseInt(process.env.SMTP_PORT || "587");
    const user = process.env.SMTP_USER || "";
    const pass = process.env.SMTP_PASS || "";

    console.log(`[Order Notification] Creating email alert for svaofficials@gmail.com...`);
    
    const itemsList = Array.isArray(order.items) 
      ? order.items 
      : (typeof order.items === 'string' ? JSON.parse(order.items) : []);

    const itemsHtml = itemsList.map((item: any) => `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #333; color: #fff; font-size: 13px;">
          <strong style="color: #d97706;">${String(item.perfumeId).toUpperCase()}</strong> (${item.size || '100 ML'})
          ${item.isCustomized ? '<br/><span style="color:#f59e0b; font-size:11px;">[Customized Corporate Gift]</span>' : ''}
          ${item.recipientName ? `<br/><span style="font-size:11px; color:#9ca3af;">Recipient: ${item.recipientName}</span>` : ''}
          ${item.message ? `<br/><span style="font-size:11px; color:#9ca3af; font-style:italic;">Engraving text: "${item.message}"</span>` : ''}
        </td>
        <td style="padding: 10px; border-bottom: 1px solid #333; color: #fff; font-size: 13px; text-align: center;">
          ${item.quantity}
        </td>
        <td style="padding: 10px; border-bottom: 1px solid #333; color: #d97706; font-size: 13px; text-align: right; font-weight: bold;">
          ₹${item.unitPrice}
        </td>
      </tr>
    `).join('');

    const emailContent = `
      <div style="background-color: #0b0c0e; color: #f3f4f6; padding: 30px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 2px solid #d97706;">
        <h1 style="color: #d97706; border-bottom: 1px solid #d97706; padding-bottom: 15px; text-align: center; font-size: 24px; tracking-widest: 4px; text-transform: uppercase; font-family: Georgia, serif;">VICTNOW REGISTRY</h1>
        <h2 style="text-align: center; font-size: 14px; letter-spacing: 2px; color: #9ca3af; text-transform: uppercase; margin-bottom: 30px;">Premium Dispatch Notification</h2>
        
        <p style="font-size: 13px; line-height: 1.6; color: #e5e7eb;">
          A luxury purchase has been securely processed on the VICTNOW client portal. Below is the dispatch manifest:
        </p>

        <table style="width: 100%; border-collapse: collapse; margin: 25px 0; background-color: #121418; border: 1px solid #2d2f36;">
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase; width: 35%; border-bottom: 1px solid #1a1c23;">Client Name:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px; border-bottom: 1px solid #1a1c23;">${order.customer_name}</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase; border-bottom: 1px solid #1a1c23;">Client Email:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px; border-bottom: 1px solid #1a1c23;">${order.customer_email}</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase; border-bottom: 1px solid #1a1c23;">Contact Number:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px; border-bottom: 1px solid #1a1c23;">${order.customer_phone}</td>
          </tr>
          ${order.company ? `
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase; border-bottom: 1px solid #1a1c23;">Corporate Entity:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px; border-bottom: 1px solid #1a1c23;">${order.company}</td>
          </tr>` : ''}
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase; border-bottom: 1px solid #1a1c23;">Delivery Suite:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px; border-bottom: 1px solid #1a1c23;">${order.address}, ${order.city} (Zip: ${order.zip})</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #d97706; font-size: 11px; text-transform: uppercase;">Payment Securement:</td>
            <td style="padding: 12px; color: #fff; font-size: 13px;">${order.payment_method}</td>
          </tr>
        </table>

        <h3 style="margin-top: 30px; color: #d97706; border-bottom: 1px solid #2d2f36; padding-bottom: 8px; font-size: 12px; text-transform: uppercase; letter-spacing: 1px;">Selected Fragrance Allocations</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background-color: #16171b; border-bottom: 2px solid #d97706;">
              <th style="padding: 10px; text-align: left; color: #d97706; font-size: 10px; text-transform: uppercase;">Aroma & Specifications</th>
              <th style="padding: 10px; text-align: center; color: #d97706; font-size: 10px; text-transform: uppercase; width: 15%;">Qty</th>
              <th style="padding: 10px; text-align: right; color: #d97706; font-size: 10px; text-transform: uppercase; width: 25%;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
          <tfoot>
            <tr>
              <td colspan="2" style="padding: 15px 10px; font-weight: bold; text-align: right; color: #d97706; font-size: 13px; text-transform: uppercase;">Grand Registry Total:</td>
              <td style="padding: 15px 10px; font-weight: bold; text-align: right; color: #fff; font-size: 16px;">₹${order.total_price}</td>
            </tr>
          </tfoot>
        </table>

        <div style="margin-top: 40px; text-align: center; border-top: 1px solid #2d2f36; padding-top: 25px; font-size: 11px; color: #6b7280; line-height: 1.5;">
          <p style="margin: 0; font-weight: bold; color: #9ca3af;">VICTNOW Luxury Perfumeries Dispatch Advisory</p>
          <p style="margin: 5px 0 0 0; color: #4b5563;">This notification contains confidential buyer credentials. Do not forward.</p>
        </div>
      </div>
    `;

    if (user && pass) {
      const transporter = nodemailer.createTransport({
        host,
        port,
        secure: port === 465,
        auth: { user, pass }
      });

      const info = await transporter.sendMail({
        from: `"VICTNOW Executive Office" <${user}>`,
        to: "svaofficials@gmail.com",
        subject: `[NEW ORDER ALERT] VICTNOW Luxury Purchase: ${order.customer_name}`,
        html: emailContent
      });

      console.log(`[Order Notification] Real email sent to svaofficials@gmail.com! MessageId: ${info.messageId}`);
    } else {
      console.warn(`[Order Notification] SMTP credentials not set (SMTP_USER/SMTP_PASS). Simulating receipt email dispatch...`);
      console.log(`[SIMULATED EMAIL ALERT SENT TO svaofficials@gmail.com]:\nSubject: [NEW ORDER ALERT] VICTNOW Luxury Purchase: ${order.customer_name}\nBody:\n${emailContent}`);
    }
  } catch (err: any) {
    console.error("[Order Notification] Error dispatching email:", err.message);
  }
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for parsing JSON
  app.use(express.json());

  // Database check endpoint
  app.get("/api/db-status", async (req, res) => {
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const result = await pool.query("SELECT NOW()");
      res.json({ status: "connected", time: result.rows[0].now });
    } catch (err: any) {
      res.status(500).json({ error: "Database connection failed", details: err.message });
    }
  });

  // Profiles endpoint (Upsert by email)
  app.post("/api/profiles", async (req, res) => {
    const { email, mobile, name } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.profiles (email, mobile, name, updated_at)
        VALUES ($1, $2, $3, NOW())
        ON CONFLICT (email)
        DO UPDATE SET mobile = EXCLUDED.mobile, name = EXCLUDED.name, updated_at = NOW()
        RETURNING *;
      `;
      const result = await pool.query(query, [email, mobile || "", name || null]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Profile upsert error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Client Authentication: Login by email & password
  app.post("/api/auth/login", async (req, res) => {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const result = await pool.query("SELECT * FROM public.profiles WHERE email = $1", [email]);
      if (result.rows.length === 0) {
        return res.status(401).json({ error: "No client account found with this email. Please register as a new client." });
      }
      const user = result.rows[0];
      if (user.password && user.password !== password) {
        return res.status(401).json({ error: "Incorrect security password. Please try again." });
      }
      // If the user didn't have a password set yet (legacy data), assign this password as their password!
      if (!user.password) {
        await pool.query("UPDATE public.profiles SET password = $1 WHERE id = $2", [password, user.id]);
      }
      res.json({
        success: true,
        user: {
          email: user.email,
          mobile: user.mobile,
          name: user.name || undefined
        }
      });
    } catch (err: any) {
      console.error("Auth login error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Client Authentication: Check if email already registered
  app.post("/api/auth/check-email", async (req, res) => {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const result = await pool.query("SELECT * FROM public.profiles WHERE email = $1", [email]);
      res.json({
        success: true,
        exists: result.rows.length > 0
      });
    } catch (err: any) {
      console.error("Check email error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Client Authentication: Register new user
  app.post("/api/auth/register", async (req, res) => {
    const { email, password, mobile, name } = req.body;
    if (!email || !password || !mobile) {
      return res.status(400).json({ error: "Email, contact number, and password are required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      // Check if user already exists
      const checkResult = await pool.query("SELECT * FROM public.profiles WHERE email = $1", [email]);
      if (checkResult.rows.length > 0) {
        return res.status(400).json({ error: "A client account with this email already exists. Please login instead." });
      }
      const result = await pool.query(
        `INSERT INTO public.profiles (email, mobile, name, password, updated_at)
         VALUES ($1, $2, $3, $4, NOW())
         RETURNING *`,
        [email, mobile, name || null, password]
      );
      const user = result.rows[0];
      res.json({
        success: true,
        user: {
          email: user.email,
          mobile: user.mobile,
          name: user.name || undefined
        }
      });
    } catch (err: any) {
      console.error("Auth register error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Client Activity History endpoint
  app.get("/api/profiles/:email/activities", async (req, res) => {
    const { email } = req.params;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      // Fetch orders for this email
      const ordersResult = await pool.query(
        "SELECT * FROM public.orders WHERE customer_email = $1 ORDER BY created_at DESC",
        [email]
      );
      // Fetch gifting requests for this email
      const giftingResult = await pool.query(
        "SELECT * FROM public.gifting_requests WHERE customer_email = $1 ORDER BY created_at DESC",
        [email]
      );
      res.json({
        success: true,
        orders: ordersResult.rows,
        giftingRequests: giftingResult.rows
      });
    } catch (err: any) {
      console.error("Fetch client activities error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Orders endpoint (Insert order)
  app.post("/api/orders", async (req, res) => {
    const { customer_name, customer_email, customer_phone, company, address, city, zip, items, total_price, payment_method } = req.body;
    if (!customer_email || !customer_name) {
      return res.status(400).json({ error: "Name and email are required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.orders (customer_name, customer_email, customer_phone, company, address, city, zip, items, total_price, payment_method)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        RETURNING *;
      `;
      const result = await pool.query(query, [
        customer_name,
        customer_email,
        customer_phone,
        company || null,
        address,
        city,
        zip,
        JSON.stringify(items || []),
        total_price || 0,
        payment_method
      ]);
      const orderRecord = result.rows[0];
      res.json({ success: true, data: orderRecord });

      // Dispatch order receipt alert to svaofficials@gmail.com
      sendOrderNotification(orderRecord).catch(err => {
        console.error("Async email dispatch failed:", err);
      });
    } catch (err: any) {
      console.error("Order insertion error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Gifting Requests endpoint (Insert custom gifting design)
  app.post(["/api/gifting-requests", "/api/gifting_requests"], async (req, res) => {
    const { perfume_id, size, quantity, recipient_name, message, font_style, ribbon_color, customer_email, customer_phone } = req.body;
    if (!customer_email) {
      return res.status(400).json({ error: "Customer email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.gifting_requests (perfume_id, size, quantity, recipient_name, message, font_style, ribbon_color, customer_email, customer_phone)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        RETURNING *;
      `;
      const result = await pool.query(query, [
        perfume_id,
        size,
        quantity || 1,
        recipient_name || "",
        message || "",
        font_style || "",
        ribbon_color || "",
        customer_email,
        customer_phone || null
      ]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Gifting request insertion error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Get all products (Public)
  app.get("/api/products", async (req, res) => {
    if (!pool) {
      return res.json({ success: true, isFallback: true, data: [] });
    }
    try {
      const result = await pool.query("SELECT * FROM public.products ORDER BY id ASC");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      console.error("Fetch products error:", err);
      res.json({ success: true, isFallback: true, error: err.message, data: [] });
    }
  });

  // Request Invitation (Public)
  app.post("/api/invitations", async (req, res) => {
    const { email, vip_code } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.invitations (email, vip_code)
        VALUES ($1, $2)
        ON CONFLICT (email)
        DO UPDATE SET vip_code = EXCLUDED.vip_code
        RETURNING *;
      `;
      const code = vip_code || `VIP-${Math.floor(1000 + Math.random() * 9000)}`;
      const result = await pool.query(query, [email, code]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Invitation insertion error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Razorpay Lazy Initialization Helper
  let razorpayInstance: any = null;

  function getRazorpay() {
    if (!razorpayInstance) {
      const keyId = process.env.RAZORPAY_KEY_ID;
      const keySecret = process.env.RAZORPAY_KEY_SECRET;
      if (!keyId || !keySecret) {
        console.warn("Razorpay API credentials (RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET) missing in env. Running in Sandbox Simulator mode.");
        return null;
      }
      try {
        const RZP = (Razorpay as any).default || Razorpay;
        razorpayInstance = new RZP({
          key_id: keyId,
          key_secret: keySecret
        });
      } catch (err) {
        console.error("Failed to initialize Razorpay SDK:", err);
        return null;
      }
    }
    return razorpayInstance;
  }

  // Razorpay Config Check
  app.get("/api/razorpay/config", (req, res) => {
    res.json({
      keyId: process.env.RAZORPAY_KEY_ID || "rzp_test_MOCK_KEY_ID",
      isMock: !process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET
    });
  });

  // Razorpay Order Creation
  app.post("/api/razorpay/create-order", async (req, res) => {
    const { amount, currency } = req.body;
    if (!amount) {
      return res.status(400).json({ error: "Amount is required" });
    }
    const rzp = getRazorpay();
    const curr = currency || "INR";
    const amountInPaisa = Math.round(amount * 100);

    if (!rzp) {
      // Mock order for sandbox simulator
      const mockOrderId = "order_mock_" + Math.floor(100000 + Math.random() * 900000);
      return res.json({
        id: mockOrderId,
        amount: amountInPaisa,
        currency: curr,
        isMock: true
      });
    }

    try {
      const order = await rzp.orders.create({
        amount: amountInPaisa,
        currency: curr,
        receipt: "receipt_order_" + Date.now()
      });
      res.json(order);
    } catch (err: any) {
      console.error("Razorpay SDK order creation error:", err);
      res.status(500).json({ error: err.message || "Failed to create Razorpay order" });
    }
  });

  // Razorpay Signature Verification
  app.post("/api/razorpay/verify-payment", async (req, res) => {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature, isMock } = req.body;

    if (isMock || (razorpay_order_id && razorpay_order_id.startsWith("order_mock_"))) {
      return res.json({ success: true, verified: true, isMock: true });
    }

    const keySecret = process.env.RAZORPAY_KEY_SECRET;
    if (!keySecret) {
      return res.status(500).json({ error: "Razorpay secrets not configured on server" });
    }

    try {
      const text = razorpay_order_id + "|" + razorpay_payment_id;
      const generated_signature = crypto
        .createHmac("sha256", keySecret)
        .update(text)
        .digest("hex");

      if (generated_signature === razorpay_signature) {
        res.json({ success: true, verified: true });
      } else {
        res.status(400).json({ error: "Razorpay signature verification failed" });
      }
    } catch (err: any) {
      res.status(500).json({ error: err.message || "Failed to verify signature" });
    }
  });

  // Admin credentials store configuration
  const CREDENTIALS_FILE = path.join(process.cwd(), "admin-credentials-store.json");

  function getAdminCredentials() {
    try {
      if (fs.existsSync(CREDENTIALS_FILE)) {
        const data = JSON.parse(fs.readFileSync(CREDENTIALS_FILE, "utf-8"));
        if (data.username && data.password) {
          return data;
        }
      }
    } catch (err) {
      console.error("Error reading admin credentials file:", err);
    }
    const username = process.env.ADMIN_USERNAME || "admin";
    const password = process.env.ADMIN_PASSWORD || "adminpassword";
    try {
      fs.writeFileSync(CREDENTIALS_FILE, JSON.stringify({ username, password }, null, 2));
    } catch (err) {
      // Ignored
    }
    return { username, password };
  }

  const ADMIN_TOKEN = "Bearer admin-secret-session-token-9988";

  // Admin Authentication Middleware
  const requireAdminAuth = (req: express.Request, res: express.Response, next: express.NextFunction) => {
    const authHeader = req.headers.authorization;
    if (!authHeader || authHeader !== ADMIN_TOKEN) {
      return res.status(401).json({ error: "Unauthorized access to administrator APIs" });
    }
    next();
  };

  // Admin: Login endpoint
  app.post("/api/admin/login", (req, res) => {
    const { username, password } = req.body;
    const creds = getAdminCredentials();
    if (username === creds.username && password === creds.password) {
      res.json({ success: true, token: "admin-secret-session-token-9988" });
    } else {
      res.status(401).json({ error: "Invalid admin username or password" });
    }
  });

  // Admin: Verify developer access key (Server-side validation for access gate)
  app.post("/api/admin/verify-access-key", (req, res) => {
    const { key } = req.body;
    const expectedKey = process.env.ADMIN_CONSOLE_ACCESS_KEY || "ceoviju";
    if (key && key.toLowerCase() === expectedKey.toLowerCase()) {
      res.json({ success: true, token: "admin-secret-session-token-9988" });
    } else {
      res.status(401).json({ error: "Access Denied. Invalid Developer Key." });
    }
  });

  // Admin: Change credentials endpoint
  app.post("/api/admin/change-credentials", requireAdminAuth, (req, res) => {
    const { username, password } = req.body;
    if (!username || !password || username.trim() === "" || password.trim() === "") {
      return res.status(400).json({ error: "Username and password cannot be empty" });
    }
    try {
      fs.writeFileSync(CREDENTIALS_FILE, JSON.stringify({ username: username.trim(), password: password.trim() }, null, 2));
      res.json({ success: true, message: "Admin credentials updated successfully" });
    } catch (err: any) {
      res.status(500).json({ error: "Failed to save new credentials: " + err.message });
    }
  });

  // Admin: Get all profiles
  app.get("/api/admin/profiles", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.profiles ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all orders
  app.get("/api/admin/orders", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.orders ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all gifting requests
  app.get(["/api/admin/gifting-requests", "/api/admin/gifting_requests"], requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.gifting_requests ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all products
  app.get("/api/admin/products", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.products ORDER BY id ASC");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Update product details (image, description, limited edition toggle)
  app.post("/api/admin/products/:id", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    const { id } = req.params;
    const { image_url, description, is_limited_edition, price } = req.body;
    try {
      const query = `
        UPDATE public.products 
        SET image_url = COALESCE($1, image_url),
            description = COALESCE($2, description),
            is_limited_edition = COALESCE($3, is_limited_edition),
            price = COALESCE($4, price)
        WHERE id = $5
        RETURNING *;
      `;
      const result = await pool.query(query, [
        image_url !== undefined ? image_url : null,
        description !== undefined ? description : null,
        is_limited_edition !== undefined ? is_limited_edition : null,
        price !== undefined ? price : null,
        id
      ]);
      if (result.rows.length === 0) {
        return res.status(404).json({ error: "Product not found" });
      }
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Admin update product error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all invitations
  app.get("/api/admin/invitations", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.invitations ORDER BY created_at DESC LIMIT 200");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Clear database tables for fresh testing
  app.post("/api/admin/clear-data", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const { table } = req.body;
      if (!table || !["profiles", "orders", "gifting_requests", "invitations", "products"].includes(table)) {
        return res.status(400).json({ error: "Invalid table specified" });
      }
      await pool.query(`TRUNCATE TABLE public.${table} RESTART IDENTITY CASCADE`);
      res.json({ success: true, message: `Successfully truncated table ${table}` });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Connection Diagnostics for Postgres and Supabase services
  app.get("/api/admin/diagnose", requireAdminAuth, async (req, res) => {
    const diagnostics: any = {
      timestamp: new Date().toISOString(),
      database: { status: "checking", message: "", latency: 0 },
      restApi: { status: "checking", message: "", url: "" },
      authService: { status: "checking", message: "", url: "" }
    };

    // 1. Database connection check
    if (!pool) {
      diagnostics.database = {
        status: "failed",
        message: "PostgreSQL client pool is uninitialized. Verify DATABASE_URL setting."
      };
    } else {
      const dbStart = Date.now();
      try {
        const result = await pool.query("SELECT NOW()");
        diagnostics.database = {
          status: "healthy",
          message: `SQL check succeeded! Direct Postgres query response time is low. Server time: ${result.rows[0].now}`,
          latency: Date.now() - dbStart
        };
      } catch (err: any) {
        diagnostics.database = {
          status: "failed",
          message: `SQL connection failed: ${err.message}`,
          latency: Date.now() - dbStart
        };
      }
    }

    // 2. REST API endpoint check
    const supabaseUrl = (process.env.VITE_SUPABASE_URL || "https://qfabhexouufjeyipxoes.supabase.co").trim();
    diagnostics.restApi.url = `${supabaseUrl}/rest/v1/`;
    diagnostics.authService.url = `${supabaseUrl}/auth/v1/health`;

    const restStart = Date.now();
    try {
      const restRes = await fetch(diagnostics.restApi.url);
      const statusText = restRes.status;
      diagnostics.restApi = {
        ...diagnostics.restApi,
        status: "healthy",
        message: `Rest API is reachable. Server responded with HTTP status ${statusText} (${restRes.statusText || 'Active'})`,
        latency: Date.now() - restStart
      };
    } catch (err: any) {
      diagnostics.restApi = {
        ...diagnostics.restApi,
        status: "failed",
        message: `REST API request failed: ${err.message}`,
        latency: Date.now() - restStart
      };
    }

    // 3. Auth service check
    const authStart = Date.now();
    try {
      const authRes = await fetch(diagnostics.authService.url);
      const authData = await authRes.json().catch(() => ({}));
      diagnostics.authService = {
        ...diagnostics.authService,
        status: authRes.ok || authRes.status === 200 ? "healthy" : "warning",
        message: `Auth microservice is healthy. Server returned HTTP status ${authRes.status}. Payload: ${JSON.stringify(authData)}`,
        latency: Date.now() - authStart
      };
    } catch (err: any) {
      diagnostics.authService = {
        ...diagnostics.authService,
        status: "failed",
        message: `Auth service request failed: ${err.message}`,
        latency: Date.now() - authStart
      };
    }

    res.json({ success: true, diagnostics });
  });

  // Vite middleware for asset serving and HMR handling in development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // SPA fallback
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  // Initialize DB tables
  await initializeDatabase();

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
