import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import pg from "pg";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

const { Pool } = pg;

// Get connection string from environment
const connectionString = process.env.DATABASE_URL;

let pool: pg.Pool | null = null;

if (connectionString) {
  console.log("Initializing database pool with connection string...");
  pool = new Pool({
    connectionString,
    ssl: {
      rejectUnauthorized: false // Required for Supabase/hosted databases
    }
  });
} else {
  console.error("WARNING: DATABASE_URL env variable is not set!");
}

async function initializeDatabase() {
  if (!pool) return;
  try {
    console.log("Ensuring database tables exist...");
    
    // Create profiles table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        mobile TEXT NOT NULL,
        name TEXT,
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    
    // Create orders table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_name TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT NOT NULL,
        company TEXT,
        address TEXT NOT NULL,
        city TEXT NOT NULL,
        zip TEXT NOT NULL,
        items JSONB NOT NULL DEFAULT '[]'::jsonb,
        total_price NUMERIC(10, 2) NOT NULL,
        payment_method TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    
    // Create gifting_requests table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.gifting_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        perfume_id TEXT NOT NULL,
        size TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        recipient_name TEXT NOT NULL,
        message TEXT NOT NULL,
        font_style TEXT NOT NULL,
        ribbon_color TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    
    console.log("All database tables checked/created successfully!");
  } catch (err) {
    console.error("Database initialization error:", err);
  }
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for parsing JSON
  app.use(express.json());

  // Database check endpoint
  app.get("/api/db-status", async (req, res) => {
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const result = await pool.query("SELECT NOW()");
      res.json({ status: "connected", time: result.rows[0].now });
    } catch (err: any) {
      res.status(500).json({ error: "Database connection failed", details: err.message });
    }
  });

  // Profiles endpoint (Upsert by email)
  app.post("/api/profiles", async (req, res) => {
    const { email, mobile, name } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.profiles (email, mobile, name, updated_at)
        VALUES ($1, $2, $3, NOW())
        ON CONFLICT (email)
        DO UPDATE SET mobile = EXCLUDED.mobile, name = EXCLUDED.name, updated_at = NOW()
        RETURNING *;
      `;
      const result = await pool.query(query, [email, mobile || "", name || null]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Profile upsert error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Orders endpoint (Insert order)
  app.post("/api/orders", async (req, res) => {
    const { customer_name, customer_email, customer_phone, company, address, city, zip, items, total_price, payment_method } = req.body;
    if (!customer_email || !customer_name) {
      return res.status(400).json({ error: "Name and email are required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.orders (customer_name, customer_email, customer_phone, company, address, city, zip, items, total_price, payment_method)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        RETURNING *;
      `;
      const result = await pool.query(query, [
        customer_name,
        customer_email,
        customer_phone,
        company || null,
        address,
        city,
        zip,
        JSON.stringify(items || []),
        total_price || 0,
        payment_method
      ]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Order insertion error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Gifting Requests endpoint (Insert custom gifting design)
  app.post("/api/gifting-requests", async (req, res) => {
    const { perfume_id, size, quantity, recipient_name, message, font_style, ribbon_color, customer_email, customer_phone } = req.body;
    if (!customer_email) {
      return res.status(400).json({ error: "Customer email is required" });
    }
    if (!pool) {
      return res.status(500).json({ error: "Database not configured" });
    }
    try {
      const query = `
        INSERT INTO public.gifting_requests (perfume_id, size, quantity, recipient_name, message, font_style, ribbon_color, customer_email, customer_phone)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        RETURNING *;
      `;
      const result = await pool.query(query, [
        perfume_id,
        size,
        quantity || 1,
        recipient_name || "",
        message || "",
        font_style || "",
        ribbon_color || "",
        customer_email,
        customer_phone || null
      ]);
      res.json({ success: true, data: result.rows[0] });
    } catch (err: any) {
      console.error("Gifting request insertion error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Admin credentials from environment variables or secure defaults
  const ADMIN_USER = process.env.ADMIN_USERNAME || "admin";
  const ADMIN_PASS = process.env.ADMIN_PASSWORD || "adminpassword";
  const ADMIN_TOKEN = "Bearer admin-secret-session-token-9988";

  // Admin Authentication Middleware
  const requireAdminAuth = (req: express.Request, res: express.Response, next: express.NextFunction) => {
    const authHeader = req.headers.authorization;
    if (!authHeader || authHeader !== ADMIN_TOKEN) {
      return res.status(401).json({ error: "Unauthorized access to administrator APIs" });
    }
    next();
  };

  // Admin: Login endpoint
  app.post("/api/admin/login", (req, res) => {
    const { username, password } = req.body;
    if (username === ADMIN_USER && password === ADMIN_PASS) {
      res.json({ success: true, token: "admin-secret-session-token-9988" });
    } else {
      res.status(401).json({ error: "Invalid admin username or password" });
    }
  });

  // Admin: Get all profiles
  app.get("/api/admin/profiles", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.profiles ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all orders
  app.get("/api/admin/orders", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.orders ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Get all gifting requests
  app.get("/api/admin/gifting-requests", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const result = await pool.query("SELECT * FROM public.gifting_requests ORDER BY created_at DESC LIMIT 100");
      res.json({ success: true, data: result.rows });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Clear database tables for fresh testing
  app.post("/api/admin/clear-data", requireAdminAuth, async (req, res) => {
    if (!pool) return res.status(500).json({ error: "Database not configured" });
    try {
      const { table } = req.body;
      if (!table || !["profiles", "orders", "gifting_requests"].includes(table)) {
        return res.status(400).json({ error: "Invalid table specified" });
      }
      await pool.query(`TRUNCATE TABLE public.${table} RESTART IDENTITY CASCADE`);
      res.json({ success: true, message: `Successfully truncated table ${table}` });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Admin: Connection Diagnostics for Postgres and Supabase services
  app.get("/api/admin/diagnose", requireAdminAuth, async (req, res) => {
    const diagnostics: any = {
      timestamp: new Date().toISOString(),
      database: { status: "checking", message: "", latency: 0 },
      restApi: { status: "checking", message: "", url: "" },
      authService: { status: "checking", message: "", url: "" }
    };

    // 1. Database connection check
    if (!pool) {
      diagnostics.database = {
        status: "failed",
        message: "PostgreSQL client pool is uninitialized. Verify DATABASE_URL setting."
      };
    } else {
      const dbStart = Date.now();
      try {
        const result = await pool.query("SELECT NOW()");
        diagnostics.database = {
          status: "healthy",
          message: `SQL check succeeded! Direct Postgres query response time is low. Server time: ${result.rows[0].now}`,
          latency: Date.now() - dbStart
        };
      } catch (err: any) {
        diagnostics.database = {
          status: "failed",
          message: `SQL connection failed: ${err.message}`,
          latency: Date.now() - dbStart
        };
      }
    }

    // 2. REST API endpoint check
    const supabaseUrl = (process.env.VITE_SUPABASE_URL || "https://qfabhexouufjeyipxoes.supabase.co").trim();
    diagnostics.restApi.url = `${supabaseUrl}/rest/v1/`;
    diagnostics.authService.url = `${supabaseUrl}/auth/v1/health`;

    const restStart = Date.now();
    try {
      const restRes = await fetch(diagnostics.restApi.url);
      const statusText = restRes.status;
      diagnostics.restApi = {
        ...diagnostics.restApi,
        status: "healthy",
        message: `Rest API is reachable. Server responded with HTTP status ${statusText} (${restRes.statusText || 'Active'})`,
        latency: Date.now() - restStart
      };
    } catch (err: any) {
      diagnostics.restApi = {
        ...diagnostics.restApi,
        status: "failed",
        message: `REST API request failed: ${err.message}`,
        latency: Date.now() - restStart
      };
    }

    // 3. Auth service check
    const authStart = Date.now();
    try {
      const authRes = await fetch(diagnostics.authService.url);
      const authData = await authRes.json().catch(() => ({}));
      diagnostics.authService = {
        ...diagnostics.authService,
        status: authRes.ok || authRes.status === 200 ? "healthy" : "warning",
        message: `Auth microservice is healthy. Server returned HTTP status ${authRes.status}. Payload: ${JSON.stringify(authData)}`,
        latency: Date.now() - authStart
      };
    } catch (err: any) {
      diagnostics.authService = {
        ...diagnostics.authService,
        status: "failed",
        message: `Auth service request failed: ${err.message}`,
        latency: Date.now() - authStart
      };
    }

    res.json({ success: true, diagnostics });
  });

  // Vite middleware for asset serving and HMR handling in development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // SPA fallback
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  // Initialize DB tables
  await initializeDatabase();

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
